import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themes/theme-provider";
import { Footer } from "@/components/templates/footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Rohithreacts",
  description: "Generated by rohithreacts.dev next app",
};

import { SplashManager } from "@/components/templates/splash-manager";
import Header from "@/components/templates/header";

import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${roboto.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SplashManager>
            <div className="flex min-h-screen w-full flex-col font-(family-name:--font-inter-tight)">
              <div className="relative mx-auto flex w-full max-w-7xl flex-1 flex-col px-4">
                <Header />
                <main className="flex-1 text-center">{children}</main>

                <Footer />
              </div>
            </div>
            <Toaster />
          </SplashManager>
        </ThemeProvider>
      </body>
    </html>
  );
}
